#!/usr/bin/env bash

DIR="$(dirname "$(realpath "$0")")"
EWW_CONFIG_DIR="${EWW_CONFIG_DIR:-$(realpath "$DIR/..")}"

eww_cmd() {
    eww --config "$EWW_CONFIG_DIR" "$@"
}

case "$1" in
  up)
    pamixer --increase 5 >/dev/null 2>&1
    ;;
  down)
    pamixer --decrease 5 >/dev/null 2>&1
    ;;
  *)
    exit 1
    ;;
esac

vol=$("$DIR/volume-percent")
mute=$("$DIR/volume-mute")
class=$("$DIR/volume-class")
icon=$("$DIR/volume-icon")

eww_cmd update volume_percent="$vol" volume_mute="$mute" volume_class="$class" volume_icon_glyph="$icon" >/dev/null 2>&1
