#!/usr/bin/env bash
# Volume scroll - always 5%

# eww passes scroll amount as $1
# Positive = scroll up, Negative = scroll down

if [[ "$1" =~ ^-.*$ ]] || [ "$1" -lt 0 ]; then
    # Scroll down
    pamixer --decrease 5
else
    # Scroll up  
    pamixer --increase 5
fi
