#!/usr/bin/env bash

DIR="$(dirname "$(realpath "$0")")"
CONFIG_DIR="$(dirname "$DIR")"
svg="$($DIR/weather-svg)"

if [ -n "$svg" ]; then
  printf '%s/images/%s\n' "$CONFIG_DIR" "$svg"
else
  printf '%s/images/sun.svg\n' "$CONFIG_DIR"
fi
