#!/usr/bin/env bash

CONFIG_DIR="$(dirname "$(dirname "$(realpath "$0")")")"

eww_cmd() {
  eww --config "$CONFIG_DIR" "$@"
}

(
  eww_cmd poll weather
  eww_cmd poll weather_svg
  eww_cmd poll weather_icon_path
  eww_cmd update weather_full="$("$(dirname "$(realpath "$0")")/weather" --full)"
  eww_cmd update weather_forecast="$("$(dirname "$(realpath "$0")")/weather-data)"
) >/dev/null 2>&1 &

exit 0
