#!/usr/bin/env bash

(
  eww poll weather
  eww poll weather_svg
  eww poll weather_icon_path
  eww update weather_full="$("$(dirname "$(realpath "$0")")/weather" --full)"
  eww update weather_forecast="$("$(dirname "$(realpath "$0")")/weather-data)"
) >/dev/null 2>&1 &

exit 0
