#!/usr/bin/env bash

svg=$("$(dirname "$0")/weather-svg")
BASE_DIR="$(dirname "$(realpath "$0")")/.."
if [ -n "$svg" ]; then
  printf '%s/images/%s\n' "$BASE_DIR" "$svg"
else
  printf '%s/images/sun.svg\n' "$BASE_DIR"
fi
